
version: '2'

services:

  flask:
    image: flask_summ_dev
    restart: on-failure
    build:
      context: .
      dockerfile: ./compose/flask/Dockerfile-dev
    command: /start-dev.sh
    # depends_on:
    #   - postgres
    # env_file: dev.env
    environment:
      - DEBUG=True
      - USE_DOCKER=yes
      # - GOOGLE_APPS_API_KEY=test
    volumes:
      - .:/app
    ports:
      - "5000:5000"
      - "80:80"
      - "81:81"

