FROM ubuntu:14.04
MAINTAINER dezoito <an.dezoito@gmail.com>

ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements.txt /requirements.txt

COPY ./sh_scripts/* /
RUN /bin/bash -c "source install.sh"

RUN pip3 install -r /requirements.txt

RUN sed -i 's/\r//' /install_phantom_js.sh
RUN chmod +x /install_phantom_js.sh
RUN /install_phantom_js.sh

RUN sed -i 's/\r//' /install_nltk.sh
RUN chmod +x /install_nltk.sh
RUN /install_nltk.sh

# COPY ./compose/flask/entrypoint.sh /entrypoint.sh
# RUN sed -i 's/\r//' /entrypoint.sh
# RUN chmod +x /entrypoint.sh

COPY ./compose/flask/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh


WORKDIR /app

# Line below was commented because entrypoint.sh doesn't do anything
# and was causing issues when used in Gilab's tests (using registry image)
# ENTRYPOINT ["/entrypoint.sh"]
